[project]
name = "learning-llm"
version = "0.1.0"
description = "A from-scratch, educational implementation of a small GPT-style language model"
readme = "README.md"
authors = [
    { name = "Chandra Sagar", email = "chsagar@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "datasets>=4.1.1",
    "numpy<2",
    "tiktoken>=0.14.0",
    "tokenizers>=0.22.1",
    "torch>=2.7",
]

[project.scripts]
learning-llm = "learning_llm:main"
learning-llm-generate = "learning_llm.scripts.generate_text:main"
learning-llm-train = "learning_llm.scripts.train_tinystories_model:main"
learning-llm-train-tokenizer = "learning_llm.scripts.train_tinystories_tokenizer:main"

[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"
